steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'Hack-Syumi'
      - '--runtime=python311'
      - '--region=asia-northeast1'
      - '--source=.'
      - '--trigger-http'
      - '--entry-point=main_function'

options:
  logging: CLOUD_LOGGING_ONLY
